### ISSUE TITLE
Why gpt-2 could apply to other tasks without fine-tune?

### ISSUE THREAD

**Issue by guotong1988** [ConnorJL/GPT2#14]
Thank you!

**Comment by IanQS** [comment]
Isn't that literally one of the main points of ML? To make it generalize? 

Also, "could apply" is pretty subjective

**Comment by ConnorJL** [comment]
The idea of unsupervised learning like this is that there is a lot of unstructured, useful information present in the wide range of text the model is trained on, and it is able therefor to learn useful things even without being given a specific goal. You can read some more about this in the original [GPT2 paper](https://d4mucfpksywv.cloudfront.net/better-language-models/language_models_are_unsupervised_multitask_learners.pdf). 

Hope that helps!
