### ISSUE TITLE
Downloading Encoder Model fails

### ISSUE THREAD

**Issue by PickHub** [ConnorJL/GPT2#16]
Hi, could someone please provide me the pre-trained encoder? There seems to be an issue with the GCP  account, when I run python3 download_model.py encoder:

`<?xml version='1.0' encoding='UTF-8'?><Error><Code>UserProjectAccountProblem</Code><Message>User project billing account not in good standing.</Message><Details>The billing account for project 916430819220 is disabled in state delinquent</Details></Error>$`

**Comment by shawwn** [comment]
I ran into this too.

**Comment by ConnorJL** [comment]
Hi I'm sorry, that was a problem on my side. Has been fixed now.
