### ISSUE TITLE
A meaningful performance comparison with OpenAI's models

### ISSUE THREAD

**Issue by lostmsu** [ConnorJL/GPT2#3]
Hi Connor,

I'd like to see some meaningful comparison with released, and, if possible, unreleased OpenAI's pretrained GPT-2 models.

My concern is that if you used different training techniques, the result may be very far off from what they've got. Including a possibility, that 1.5B model could be worse, than 345M model, that they have released.

P.S. Also pinged you on Twitter about this.

**Comment by lukemelas** [comment]
Could a simple way of doing this be to report the model's perplexity on WikiText-103? 

It would be easy to compare these numbers to those in the original paper (26.4/17.5 PPL for 345/1542M).

**Comment by rusiaaman** [comment]
I tried to approximate the perplexity on Wikitext-103. Got about 59 for PrettyBig model. [Colab notebook](https://colab.research.google.com/drive/17lA1Ox0fxivhe-nDun8dy0df-bPpsMP_)

**Comment by ConnorJL** [comment]
I am working with OpenAI to produce accurate comparisons. More information will come soon.

**Comment by lukemelas** [comment]
Thanks, great to hear!

**Comment by ConnorJL** [comment]
There are now proper evaluations (done by OpenAI) [here](https://medium.com/@NPCollapse/addendum-evaluation-of-my-model-e6734b51a830)
